title: Scott Bartell
description: The personal blog of a software engineer, entrepreneur, and human.
baseurl: ""
url: "https://scottbartell.com"
twitter_username: scottbartell
github_username:  scottbartell
linkedin_username:  scottsbartell

permalink: pretty
timezone: US/Denver

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
