title: Scott Bartell
description: A blog about Ruby, Rails, Software Performance, and Maintainability
baseurl: ""
url: "https://scottbartell.com"
comments: true

future: false

permalink: pretty
timezone: US/Denver

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

comment_box:
  project_id: 5715512235393024-proj

twitter_username: ScottBartell
github_username:  ScottBartell
linkedin_username:  ScottSBartell

author: scottbartell
twitter:
  username: scottbartell
  card: summary
social:
  name: Scott Bartell
  links:
    - https://twitter.com/ScottBartell
    - https://www.linkedin.com/in/ScottSBartell
    - https://github.com/ScottBartell

relative_links:
  enabled:     true
  collections: true
